
version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${NDATABASE}
      POSTGRES_USER: ${DB_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Usa um volume nomeado
    restart: unless-stopped

volumes:
  pgdata:  # Define o volume (gerenciado pelo Docker se não existir será criado)